/**
 * P5.01e — SDK surface diff guard.
 *
 * Compares the current public surface of `@directorai/sdk` against
 * a snapshot at `docs/sdk-surface.txt`. CI fails when they diverge.
 *
 * The snapshot is intentionally a plain text file (one symbol per
 * line) so PRs surface drift in diff review. We don't use
 * api-extractor because that's another dep and we control the
 * surface size enough that line-by-line is fine.
 *
 *   pnpm sdk:surface          → diff and exit non-zero on miss
 *   pnpm sdk:surface --write  → overwrite the snapshot
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as sdk from '../packages/sdk/src/index.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const SNAPSHOT = path.join(ROOT, 'docs', 'sdk-surface.txt');

function listSurface(): string[] {
  return Object.keys(sdk).sort();
}

function formatSnapshot(symbols: readonly string[]): string {
  return `# Auto-generated by tools/sdk-surface-diff.ts — do not hand-edit.
# Refresh with: pnpm sdk:surface --write
# See: docs/guides/sdk-versioning.md

${symbols.join('\n')}
`;
}

async function loadSnapshot(): Promise<string[]> {
  try {
    const raw = await fs.readFile(SNAPSHOT, 'utf8');
    return raw
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith('#'))
      .sort();
  } catch {
    return [];
  }
}

async function main(): Promise<void> {
  const write = process.argv.includes('--write');
  const current = listSurface();

  if (write) {
    await fs.mkdir(path.dirname(SNAPSHOT), { recursive: true });
    await fs.writeFile(SNAPSHOT, formatSnapshot(current), 'utf8');
    console.info(`Snapshot updated → ${path.relative(ROOT, SNAPSHOT)} (${current.length} symbols)`);
    return;
  }

  const snapshot = await loadSnapshot();
  const added = current.filter((s) => !snapshot.includes(s));
  const removed = snapshot.filter((s) => !current.includes(s));

  if (added.length === 0 && removed.length === 0) {
    console.info(`SDK surface matches snapshot (${current.length} symbols).`);
    return;
  }

  console.error('SDK surface drift detected:');
  if (added.length) {
    console.error('\n  ADDED (re-exported but not in snapshot):');
    for (const s of added) console.error(`    + ${s}`);
  }
  if (removed.length) {
    console.error('\n  REMOVED (in snapshot but no longer exported):');
    for (const s of removed) console.error(`    - ${s}`);
  }
  console.error(
    '\nIf this is an intentional surface change, run `pnpm sdk:surface --write` and commit the snapshot.'
  );
  console.error('If unintentional, revert the re-export. See docs/guides/sdk-versioning.md.');
  process.exit(1);
}

void main();
